name: Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Enable long paths in git
        if: matrix.os == 'windows-2022'
        run: |
          git config --system core.longpaths true

      - name: Enable long paths in windows
        if: matrix.os == 'windows-2022'
        shell: powershell
        run: |
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
            -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

      - name: Checkout self
        uses: actions/checkout@v4

      - name: Checkout zed
        uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          ref: refs/tags/v0.201.9
          path: zed

      - name: Copy config file
        run: |
          cp .cargo/config.toml zed/.cargo/

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt update
          sudo apt install -y libx11-dev libasound2-dev libx11-xcb-dev libxkbcommon-dev libxkbcommon-x11-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: wasm32-wasip1

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}-${{ hashFiles('Cargo.lock') }}
          workspaces: "zed -> target"

      - name: Build
        working-directory: zed
        run: |
          cargo b -r --all-features

      - name: Archive windows build
        uses: actions/upload-artifact@v4
        with:
          name: zed-${{ matrix.os }}
          path: |
            zed/target/release/zed
            zed/target/release/zed.exe
